### ISSUE TITLE
md extension for file with metadata

### ISSUE THREAD

**Issue by allustin** [1C-Company/dt-demo-configuration#1]
MD is reserved file extension for Markdown - http://fileinfo.com/extension/md

On GitHub, Gitlab, Bitbucket, Stash and many other will be auto render this file like Markdown documents

It will be usefull to change metadata file to something like Metadata Markup Lang (*.mml) or Bussines MetaData (*.bmd)

Example is https://github.com/1C-Company/dt-demo-configuration/blob/master/DemoConfDT/AccumulationRegister.%D0%92%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D1%80%D0%B0%D1%81%D1%87%D0%B5%D1%82%D1%8B.md

Full file https://raw.githubusercontent.com/1C-Company/dt-demo-configuration/master/DemoConfDT/AccumulationRegister.%D0%92%D0%B7%D0%B0%D0%B8%D0%BC%D0%BE%D1%80%D0%B0%D1%81%D1%87%D0%B5%D1%82%D1%8B.md

**Comment by EvilBeaver** [comment]
@allustin it's 1C, dude. Issues in russian are more convenient, aren't they?

**Comment by allustin** [comment]
@EvilBeaver commit message in english, so thats why issue in English...

**Comment by pumbaEO** [comment]
Ну пока не попросили "google translate english, pleas" думаю, можно и так создавать задачи.

**Comment by znsoft** [comment]
Блин уже год пишу на гитхабе на русском и не парюсь: англоговорящим эта 1с особо не нужна , а русские думают на русском и так им гораздо проще. ну да имена файлов кодируются сложней, формат Markdown не корректно распознается github, но думаю можно написать задачу для https://github.com/mojombo ...

**Comment by SergeyDjam** [comment]
инглиш лишь для иноговорящих нужен.

**Comment by demony** [comment]
If 1C will be in english - it is a good reason to start learn english for me (and many others).

**Comment by EvilBeaver** [comment]
@znsoft, формат Markdown КОРРЕКТНО распознается github. Расширение *.md НЕКОРРЕКТНО выбрано фирмой 1С, т.к. оно уже занято форматом Markdown. В этом и суть данного issue.

**Comment by znsoft** [comment]
@EvilBeaver что собсно подтверждает мое незнание англ языка :-1:  и комментарий @pumbaEO по поводу языка :+1:

**Comment by pumbaEO** [comment]
И тишина, имхо, ответов не будет, все подумали про открытость, но Гюльчатай, всего лишь приоткрыла личико.

**Comment by EvilBeaver** [comment]
@pumbaEO ну странно было бы полагать, что будет взаимодействие вне собственного багтрекера, средствами github. В конце-концов, это репо некой конфигурации, и issues могли бы отражать ошибки в функционале этой конфигурации, а не в инструменте, которым эта конфигурация получена.

И потом, поставь себя на место 1С - в открытом форуме, где каждый может посетовать на то, что он не знает английского, на то, что он хочет ООП в 1С, на то, что любимая кошка убежала... 

Здесь сложно будет как-то разобраться в потоке флуда. А он будет, ибо новизна, всем любопытно здесь что-то написать.... Короче, момент пока не настал, это и так было ясно :)

**Comment by allustin** [comment]
@EvilBeaver попробовать на самом деле стоило. Да и ссылка на задачу остается "как артефакт". И в принципе в связи с эклипсом еще раз обострилась проблема  #2

В любом случае - на текущий момент можно сказать, что ажиотаж схлынул ;-) и необходимый конструктивный всплекс наличествует.

**Comment by 1C-Company** [comment]
Выпущена исправительная версия CTP-1.0.1.15. Расширение файлов изменено на mdo (MetaData Object).

**Comment by allustin** [comment]
Спасибо большое.
