### ISSUE TITLE
Correct project structure

### ISSUE THREAD

**Issue by MinimaJack** [1C-Company/dt-demo-configuration#2]
```
../
./src/main/_1c/
./src/main/_1c/DataProcessors/Ob1/ManagerModule.bsl
./src/main/_1c/DataProcessors/Ob1/ObjectModule.bsl
./src/main/resources/
./src/test/_1c/...
```
почему отошли от стандарта?

**Comment by 1C-Company** [comment]
@MinimaJack мы анализируем различные варианты структуры проекта. текущий вариант не является окончательным

**Comment by MinimaJack** [comment]
@1C-Company Нормальная ситуация создать "описание проблемы", что бы видеть текущие проблемы и не задавать вопросы несколько раз. Чем больше написано проблем - тем лучше вам же.

**Comment by allustin** [comment]
@1C-Company мы со своей стороны тоже проводили анализ корректной структуры на основе выгрузки в файлы:

то что у нас получалось: https://bitbucket.org/Shenja/elementaltrade/src/b909046bfff26ff60bca54c8af738e8a02aab2fa/src/?at=master
есть еще пробы пера http://habrahabr.ru/post/248303/
и соответственно пример https://github.com/elisy/ssl

По итогам анализа была даже зарегистрирована ошибка платформы за номером 10119794 - связанная с длинной имени файла если НЕ использовать каталоги.

Надеюсь данная информация будет полезна.

**Comment by 1C-Company** [comment]
@MinimaJack все верно, вместе мы сделаем продукт лучше.

@allustin  Спасибо за информацию!

**Comment by allustin** [comment]
@1C-Company когда мы анализировали структуру хранения конфигураций в исходных файлах мы исходили из того, что самое главное в исходных файлах (то есть цель) - это **обеспечить удобное объединение (merge) и удобное разрешение конфликтов (resolve conflicts) при коллективной разработке**

То есть сделать так, чтобы можно было использовать git-flow в качестве системы управления коллективного владения исходным кодом.

ключевым здесь виделась возможность удобного *http://git-scm.com/docs/git-cherry-pick* - это одна из повседневных задач - когда в финальном релизе конфигурации должна оказаться только часть функционала (отдельный коммит) из соседних веток.

Поэтому в идеале - объект метаданных: это НЕ один файл формата XML, YAML, а комплект файлов.

Тогда достигается простота разрешения конфликтов метаданных, за счет того, что конфликт происходит только на уровне отдельного компонента метаданных (одного файла), остальные файлы не затрагиваются.

То есть - для правильного выбора хранения структуры проекта необходимо обеспечить конфликт в коллективной разработке и посмотреть - каким образом структура проекта адаптирована под автоматическое разрешение конфликтов которое встроено сейчас во все известные SCM (системы владения исходными кодами).

P.S. Плюс надо понимать - что тот же git адаптирован под небольшие помещение в большом количестве файлов и НЕ очень любит исходники с большими файлами, а наоборот - много маленьких файлов.

**Comment by enik-ua** [comment]
Есть предложение воспроизвести иерархическую структуру, как в дереве конфигурации.

**Comment by wwall** [comment]
не стоит. длина имени файла - не резиновая....

**Comment by MinimaJack** [comment]
идея воспроизвести иерархическую структуру вполне нормальная
[ТУТ](https://bitbucket.org/Shenja/elementaltrade/src/b909046bfff26ff60bca54c8af738e8a02aab2fa/src/?at=master) все хорошо выглядит. 
Единственно - переименовать:
```
Report / БалансДвиженияДенег /БалансДвиженияДенег.xml
```
в
```
Report / БалансДвиженияДенег /index.xml (mdo)
```
Имя папки - синоним, одинаковые папки не создать, как и синонимов не прописать.
скопировал -> переименовал папочку -> готово, новый отчет; не надо лезть внутрь для манипулирования именами файлов.

**Comment by allustin** [comment]
Новость прошла по Зазеркалью - http://v8.1c.ru/o7/201507xml/index.htm

**Comment by 1C-Company** [comment]
Реализована иерархическая структура проекта и не только. Дальше будем смотреть на сколько удобно с ней работать. Комментарии приветствуются =)

посмотреть можно здесь - https://releases.1c.ru/version_files?nick=DevelopmentTools10&ver=1.1.0.203

**Comment by allustin** [comment]
спасибо уже пробуем - новость прошла официальными каналами http://www.1c.ru/news/info.jsp?id=20494

**Comment by artbear** [comment]
>бранч https://github.com/1C-Company/dt-demo-configuration/tree/ctp-1.1.0

@1C-Company Похоже, что EDT и 1С используют разные версии иерархической выгрузки конфигурации :)

Я провел небольшое исследование, зная про различные грабли с текстовым представлением конфигураций.
У меня лично есть явные различия с представленным Вами вариантом.

Скачал 1С 8.3.7.1633, выполнил штатную иерархическую выгрузку, получил следующие расхождения:

1 Модули объектов при типовой выгрузке 1С выгружаются как
  - `DataProcessors\xddTestRunner\Ext\ObjectModule.bsl`
у Вас показана структура 
  - `DataProcessors/ПроведениеДокументов/ObjectModule.bsl`

т.е. 1С создает ненужный каталог Ext и выгружает туда модуль.
В данном случае у Вас удобнее структура, чем у типовой выгрузки 1С.

2 Макеты выгружаются еще дальше 
  - `"Reports\ТестовыйОтчетСКДДляСравнениеСЭталоном\Templates\ОсновнаяСхемаКомпоновкиДанных\Ext\Template.xml`
  - У Вас `Reports/ДинамикаПродаж/Templates/ОсновнаяСхемаКомпоновкиДанных/Template.dcs`

В данном случае и у Вас, и у штатной выгрузки 1С структура не так удобна.

3 Что интересно, у штатной выгрузки 1С хмл-файлы описания макетов находятся в одном каталоге :) 
  - `DataProcessors\xddTestRunner\Templates\Макет.xml`
  - `DataProcessors\xddTestRunner\Templates\ОтчетТестирования.xml`

Вопросы:
1. Как Вы совмещаете 2 вида выгрузки - EDT и 1С ?
2. Зачем так далеко укладывать файлы, которые все уникальны и их можно положить в один общий каталог? 1С в своем стремлении сделать все иерархически пошла слишком далеко, часть файлов удобно положить в одном общем каталоге (я про макеты и модули объектов)

В нашем открытом продукте https://github.com/xDrivenDevelopment/v83unpack этой проблемы нет.
Например, модуль лежит на верхнем уровне выгрузки объекта, [макеты лежат в одном каталоге ](https://github.com/xDrivenDevelopment/v83unpack/tree/develop/src/bin/%D0%92%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B0%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%B8/%D0%9C%D0%B0%D0%BA%D0%B5%D1%82%D1%8B/)
