### ISSUE TITLE
Перенести служебные файлы в служебный каталог .graphite

### ISSUE THREAD

**Issue by allustin** [1C-Company/dt-demo-configuration#4]
Сейчас в корне структуру проекта есть "некрасивые файлы" и некрасивые каталоги

* каталог DT-INF
* каталог .settings
* файл project

фактически все они являются служебными и относятся НЕ к самому прикладному решению, а к настройкам IDE при работе с исходными файлами прикладного решения

вместе с этим есть уже известная практика как быть с такими файлами - в JetBrains Idea для этого используется служебный каталог **.idea**

предложил бы перенести эти файлы именно в служебный каталог - пусть он даже называется **.graphite**

**Comment by MinimaJack** [comment]
DT-INF - я так понимаю настройки конфигурации и сборки проекта. Не еклипса, а именно конфигурации - нужен 100%.

а вообще в данном случае могу посоветовать добавить в gitignore - тогда их просто не будет в репо...
```
*.project
*.settings/
```

**Comment by pumbaEO** [comment]
Вообще ситуация неодназначая, вопрос в том, что именно хранить в git. 
Вариант когда у всех разработчиков edt - все в формате который edt преобразовывает, с ограничением по деплою, т.к. только ручной(это бред, но кто-то еще этим пользуется). 

Вариант когда у части edt и у части 1c (например редактируют те объекты которые еще не реализованы в edt) - тут возникает множество вопросов, т.к. сама платформа понимает свою структктуру иерархическую или же плоскую без разнцы, а у edt своя структура. 
И сейчас нет никакой утилиты в командом режиме, которая бы преобразовала проект edt в каталог с исходниками для самой 1с. 
Если копнуть чуть дальше, то возникает проблема с деплоем конфигурации, т.е. имея исходники в формает edt мы не можем на build сервере сделать git pull, собрать автоматически cf файл, т.к. опять таки у нас нет возможности преобразовать в автоматическом режиме проект edt в проект 1с, что-бы потом запустить 1с в командном режиме загрузить исходники в cf и получить в результате последний cf файл. 
Как не крути только тупой ручной труд, по созданию cf файла.

**Comment by MinimaJack** [comment]
если в edt есть возможность конвертировать - по факту можно и без edt конвертировать(деплоить), используя плагины из edt

**Comment by 1C-Company** [comment]
> Сейчас в корне структуру проекта есть "некрасивые файлы" и некрасивые каталоги
> 
> * каталог DT-INF
> * каталог .settings
> * файл .project
> фактически все они являются служебными и относятся НЕ к самому прикладному решению, 
> а к настройкам IDE при работе с исходными файлами прикладного решения

это не совсем так.
<b>DT-INF </b> настройки проекта конфигурации (пока что содержат только информацию о версии Платформы под которую разрабатывается конфигурация).

<b>каталог .settings и файл .project</b> это стандартные артефакты проекта в Eclipse. За расположение(работу с ними) этих файлов отвечают коровые бандлы Eclipse, они не спроектированы так чтобы это можно было легко менять. Также нельзя сказать, что эти файлы не важны для проекта конфигурации, потому как содержат, например, информацию о кодировке файлов, каким билдером собирается проект, параметры проверки модулей и др.
